version: "3.9"
services:
  backend:
    container_name: backend
    build:
        context: .
        dockerfile: SurveyDemo/Dockerfile
    ports:
        - 8080:8080
    depends_on:
      - postgres
  postgres:
    container_name: postgres
    image: postgres:latest
    environment: 
        POSTGRES_USER: postgres
        POSTGRES_PASSWORD: 1234
        POSTGRES_DB: postgres
    ports:
         - 5433:5432
    volumes:
        - ./CreateTablesAndValues.sql:/docker-entrypoint-initdb.d/CreateTablesAndValues.sql
